management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /admin
  endpoint:
    health:
      show-details: always
info:
  app:
    name: "spring-boot-actuator"
    description: "Spring Boot Actuator and Admin dashboard"
    version: 0.0.1

